#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "mcp[cli]>=1.0.0",
#     "pandas>=2.0.0"
# ]
# ///

"""
Automation MCP Server

This MCP server provides tools to query an automation database (CSV file)
and retrieve automation script templates that can be generated by an agent.

Key Concepts Demonstrated:
- FastMCP server with multiple tools
- CSV data querying with pandas
- Structured data return for agent consumption
- Resource exposure for database metadata
"""

from mcp.server.fastmcp import FastMCP
import pandas as pd
from typing import List, Optional
import os

# Initialize FastMCP server with a descriptive name
# This name appears in MCP client connections and logs
mcp = FastMCP("automation-database-server")

# Path to the automation database CSV file
# Using os.path.join ensures cross-platform compatibility
DB_PATH = os.path.join(os.path.dirname(__file__), "automations_database.csv")


# ============================================================================
# TOOL 1: List All Automations
# ============================================================================
@mcp.tool(
    name="list_all_automations",
    description="Get a list of all available automation scripts in the database. "
                "Returns automation ID, name, description, and category."
)
def list_all_automations() -> str:
    """
    Retrieve all automation entries from the database.

    This tool provides an overview of all available automations without
    including the full script templates, making it useful for browsing.

    Returns:
        A formatted string with all automation metadata (excluding templates)
    """
    try:
        # Read the CSV database using pandas
        df = pd.read_csv(DB_PATH)

        # Select only metadata columns (not the full template)
        metadata = df[['id', 'name', 'description', 'category', 'script_type']]

        # Convert to a readable string format
        return metadata.to_string(index=False)

    except FileNotFoundError:
        return f"Error: Database file not found at {DB_PATH}"
    except Exception as e:
        return f"Error reading database: {str(e)}"


# ============================================================================
# TOOL 2: Search by Category
# ============================================================================
@mcp.tool(
    name="search_automations_by_category",
    description="Search for automation scripts by category. "
                "Categories include: File Management, System Maintenance, "
                "Database, System Monitoring, Version Control, Reporting."
)
def search_automations_by_category(category: str) -> str:
    """
    Filter automations by their category.

    Args:
        category: The category to filter by (e.g., "File Management")

    Returns:
        A formatted string with matching automations
    """
    try:
        df = pd.read_csv(DB_PATH)

        # Case-insensitive partial match for flexibility
        filtered = df[df['category'].str.contains(category, case=False, na=False)]

        if filtered.empty:
            return f"No automations found in category: {category}"

        # Return metadata without template for overview
        result = filtered[['id', 'name', 'description', 'category', 'script_type']]
        return result.to_string(index=False)

    except FileNotFoundError:
        return f"Error: Database file not found at {DB_PATH}"
    except Exception as e:
        return f"Error searching database: {str(e)}"


# ============================================================================
# TOOL 3: Get Automation by ID (Includes Full Template)
# ============================================================================
@mcp.tool(
    name="get_automation_by_id",
    description="Retrieve a specific automation script template by its ID. "
                "This returns the complete script template that can be used "
                "to generate the actual automation file."
)
def get_automation_by_id(automation_id: int) -> str:
    """
    Get the complete automation details including the script template.

    This is the key tool for retrieving the actual script code that will
    be written to a file by the agent.

    Args:
        automation_id: The unique ID of the automation (from list_all_automations)

    Returns:
        A formatted string with all automation details including the template
    """
    try:
        df = pd.read_csv(DB_PATH)

        # Filter for the specific ID
        automation = df[df['id'] == automation_id]

        if automation.empty:
            return f"No automation found with ID: {automation_id}"

        # Extract the automation data (first row since ID is unique)
        auto = automation.iloc[0]

        # Format the response with clear sections
        result = f"""
Automation Details:
==================
ID: {auto['id']}
Name: {auto['name']}
Description: {auto['description']}
Category: {auto['category']}
Script Type: {auto['script_type']}

Script Template:
================
{auto['template']}
"""
        return result

    except FileNotFoundError:
        return f"Error: Database file not found at {DB_PATH}"
    except Exception as e:
        return f"Error retrieving automation: {str(e)}"


# ============================================================================
# TOOL 4: Search by Script Type
# ============================================================================
@mcp.tool(
    name="search_by_script_type",
    description="Filter automations by script type (bash or python). "
                "Useful for finding automations in a specific language."
)
def search_by_script_type(script_type: str) -> str:
    """
    Filter automations by programming language.

    Args:
        script_type: The script type to filter by ("bash" or "python")

    Returns:
        A formatted string with matching automations
    """
    try:
        df = pd.read_csv(DB_PATH)

        # Case-insensitive match
        filtered = df[df['script_type'].str.lower() == script_type.lower()]

        if filtered.empty:
            return f"No automations found for script type: {script_type}"

        result = filtered[['id', 'name', 'description', 'category', 'script_type']]
        return result.to_string(index=False)

    except FileNotFoundError:
        return f"Error: Database file not found at {DB_PATH}"
    except Exception as e:
        return f"Error searching database: {str(e)}"


# ============================================================================
# TOOL 5: Get Database Statistics
# ============================================================================
@mcp.tool(
    name="get_database_stats",
    description="Get statistics about the automation database including "
                "total count, category breakdown, and script type distribution."
)
def get_database_stats() -> str:
    """
    Provide overview statistics about the automation database.

    Useful for understanding what's available in the database.

    Returns:
        A formatted string with database statistics
    """
    try:
        df = pd.read_csv(DB_PATH)

        stats = f"""
Automation Database Statistics:
================================
Total Automations: {len(df)}

By Category:
{df['category'].value_counts().to_string()}

By Script Type:
{df['script_type'].value_counts().to_string()}
"""
        return stats

    except FileNotFoundError:
        return f"Error: Database file not found at {DB_PATH}"
    except Exception as e:
        return f"Error retrieving stats: {str(e)}"


# ============================================================================
# RESOURCE: Database Schema
# ============================================================================
@mcp.resource("automation://database/schema")
def get_database_schema() -> str:
    """
    Expose the database schema as an MCP resource.

    Resources are static content that can be accessed without function calls.
    This is useful for providing context to the agent about data structure.

    Returns:
        A description of the database schema
    """
    return """
Automation Database Schema:
===========================

Fields:
- id (int): Unique identifier for each automation
- name (str): Short name of the automation
- description (str): Detailed description of what the automation does
- category (str): Category classification (File Management, System Maintenance, etc.)
- script_type (str): Programming language (bash, python)
- template (str): Complete script template ready to be written to a file

Usage:
1. Use list_all_automations to browse available automations
2. Use search tools to filter by category or script type
3. Use get_automation_by_id to retrieve the full script template
4. Agent can then write the template to a file with appropriate filename
"""


# ============================================================================
# Main Execution
# ============================================================================
if __name__ == "__main__":
    print("🤖 Starting Automation MCP Server...")
    print(f"📊 Database location: {DB_PATH}")
    print("🔧 Available tools:")
    print("  - list_all_automations")
    print("  - search_automations_by_category")
    print("  - get_automation_by_id")
    print("  - search_by_script_type")
    print("  - get_database_stats")
    print("\n📚 Available resources:")
    print("  - automation://database/schema")
    print("\n✨ Server running on stdio transport...")

    # Run the server with stdio transport
    # This means the server communicates via standard input/output
    # Perfect for integration with Claude Agent SDK
    mcp.run(transport="stdio")
