#!/usr/bin/env python3
# Automated Download Organizer Script
# Generated by Automation Agent
# This is an example of what the agent generates

import os
import shutil
from pathlib import Path

def organize_downloads(downloads_path):
    """Organize files by extension"""

    # File type categories
    categories = {
        'Images': ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.svg'],
        'Documents': ['.pdf', '.doc', '.docx', '.txt', '.xlsx', '.pptx'],
        'Videos': ['.mp4', '.avi', '.mov', '.mkv'],
        'Audio': ['.mp3', '.wav', '.flac', '.m4a'],
        'Archives': ['.zip', '.tar', '.gz', '.rar']
    }

    downloads = Path(downloads_path)

    for file in downloads.iterdir():
        if file.is_file():
            ext = file.suffix.lower()

            # Find category
            moved = False
            for category, extensions in categories.items():
                if ext in extensions:
                    category_path = downloads / category
                    category_path.mkdir(exist_ok=True)
                    shutil.move(str(file), str(category_path / file.name))
                    print(f'Moved {file.name} to {category}')
                    moved = True
                    break

            if not moved:
                other_path = downloads / 'Other'
                other_path.mkdir(exist_ok=True)
                shutil.move(str(file), str(other_path / file.name))
                print(f'Moved {file.name} to Other')

if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1:
        organize_downloads(sys.argv[1])
    else:
        print('Usage: python organize_downloads.py <downloads_path>')
